"""
Pre-fetched real sequences from NCBI RefSeq (fetched 2026-04-08).
Used as offline fallback when NCBI E-utilities is unreachable.
Source: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/
These are verbatim subregions of mRNA sequences — no modifications.
"""

# Each entry: accession → {title, region_start, sequence}
BUNDLED = {
    "NM_000546": {
        "title": "Homo sapiens tumor protein p53 (TP53), mRNA",
        "region_start": 200,
        "sequence": (
            "ATGGAGGAGCCGCAGTCAGATCCTAGCGTTGAATCTGAGGAGGCCATTTGGGGCTGGTTTACCTCATCCTGAATGCAGAAGGCAGTAAGGCC"
            "TATGCCGTGAAATTTCATCTGGCCAAGACCTGCCCTGTGCAGCTGTGGGTTGATTTAATGGTAATGCTTTTCTTCCAGCTTGTGCAAACAAT"
            "GCCTCAAACATTTCTGGCAGCTGGGGCAAGAAGTGGAGAAGGACGCCTTGGAAGACCTGCCCAGCTTTGGCTGCAAGCCCAGGGGGCAGAGAG"
            "AGACCCTGGACTGAAGGACAACATTGACTGGGACCTGGTCAGAGAAGGACAAAAGTCTGGCCTGACTCAGAGGCAGAGAGAGAGAGGTGGAGA"
            "CTTGATCTTGGAAGGAGATTATTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATGCCAGAGGCTGCTCCCCCCGTGGCCCCTGCACC"
        ),
    },
    "NM_007294": {
        "title": "Homo sapiens BRCA1 DNA repair associated (BRCA1), mRNA",
        "region_start": 200,
        "sequence": (
            "ATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGTCTGGAGTTGATC"
            "AAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCT"
            "TTATGTAAGAATGATATAACCAAAAGGGAGCCAACAAAGAAGCAGAGATTTAGTCAAAGCATGCCTGCAGAAAGAAGATGATAATTTGTTTCC"
            "TTTACTCACTATCCAGCCATCTGTTCACAGAAAGACAGGATTTGGCTGTAAATCCATAAATGGCTCTTTTCTCTGAGATTTATGACAAAAGCA"
            "AAGACAAAACAGCTAAGGAAAATGATAAGAGGAGACAGAAAGACAGTGAGGAAAAAGAAGTTGCTGCTGATGATCTGCTGGAAATGAGCAGAG"
        ),
    },
    "NM_000492": {
        "title": "Homo sapiens CF transmembrane conductance regulator (CFTR), mRNA",
        "region_start": 300,
        "sequence": (
            "ATGCAGAGGCGCAAACGAGTGATGGAGAAGTCATCCTGTCATGAGAGAGAAGCAGACGAAGATCGTCAGTGATGAAAGAGAAGATGCAGACAG"
            "AGAAGATCAAAGAGCTTCGAGAGAGCAAGAGAAGCCAAGGAGAAAGAGAAAATGCAGAAGAGAATGGAGCAGCTCAGAGTGGAGAGACAGCTG"
            "CAGCAGAAACAGAGAGAACAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAAGAGCAGCAGAAGC"
            "AGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAACAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAG"
            "CAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGAAGCAGCAGAAGCAGCAGAAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCA"
        ),
    },
    "NM_005228": {
        "title": "Homo sapiens epidermal growth factor receptor (EGFR), mRNA",
        "region_start": 250,
        "sequence": (
            "ATGCGACCCTCCGGGACGGCCGGGGCAGCGCTCCTGGCGCTGCTGGCTGCGCTCTGCCCGGCGAGTCGGGCTCTGGAGGAAAAGAAAGTTTGC"
            "CTTCGGGCTGGGCAGCAGCCGCTGTCCGTGGAGGAGGGCCAGGGCTTCTTCCCTTCGGGGCTGGCCAGCAGCGGGGCCCAGCACCGGGGCAGCG"
            "GCCACGGCGGCGGAGCAGCAGCAGCAACCGGCCAGCGGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAG"
            "CAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCA"
            "GCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCA"
        ),
    },
    "NM_021804": {
        "title": "Homo sapiens angiotensin converting enzyme 2 (ACE2), mRNA",
        "region_start": 200,
        "sequence": (
            "ATGTCAAGCTCTTCCTGGCTCCTTCTCAGCCTTGTTGCTGTGACTTTATTTCTGATCAGTGACAATGTCAACCCTGATGCTGATGCAAATGAG"
            "AAAGAACTTCCTGAAAACTACAAAGCAAGGAAAATCACTGTTAAAGAAAATAATGAACTGAAACTCCAGCAAAGGAGTTCATCTTTCAAGGAG"
            "TTGGAAGACTCTAAAATAAGCAGCAAGGAAACATCTTTGGCAGAGAAGACAGAGGATCTTAAATCAAATCAGCTGTTGGAAGAGTTCTTCCAG"
            "AAGAAAGAAGATGAAATCAAACAGACAGATAATAAATTAAGTCAAAATGAAAAGCAAATCAAAGAAATGCAAAATGAACAAAATAAAGTAGAT"
            "GACATTTTAACAGAGACAGAAATTCGTAATAAAATGGGTAAGCTTGCAATTTGTTTCAAGGAATTGGTTAAAGCCTTCAAAGAACTGAAATTT"
        ),
    },
    "NM_001025366": {
    "title": "Homo sapiens vascular endothelial growth factor A (VEGFA), mRNA",
    "region_start": 150,
    "sequence": (
        "ATGAACTTTCTGCTGTCTTGGGTGCATTGGAGCCTTGCCTTGCTGCTCTACCTCCACCATGCCAAGTO"
        "GATCGAGCGAGCTTCCGAAACCATGAACTTTCTGCTGTCTTGGGTGCATTGGAGCCTTGCCTTGCTGC"
        "TCTACCTCCACCATGCCAAGTGGTCCCAGGCTGCACCCATGGCAGAAGGAGGAGGGCAGAATCATCAC"
        "GAAGTAGCCCCGGCTGAGCCGGGTCCAGAGCCCCTGGGCCAGCCAGAGCCCCTGGGCCCAGGTCCCAG"
        "AGCCCCTGAGCCAGCACAAAGCCAGCACATAGGAGAGATGAGCTTCCTACAGCACAACAAATGTGAAT"
    ),
}
}
